version: '3.7'

networks:
  naturalist:
    external: true

services:

  proxy:
    image: jwilder/nginx-proxy:1.2
    container_name: jwilder-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
    networks:
      - naturalist
